"use client";

import { useMemo, useState } from "react";
import { CopyButton, Input, Label } from "@/components/ui";
import { ToolShell } from "@/components/ToolShell";

const entities = [
  [" ", "nbsp", 160, "Non-breaking space"], ["<", "lt", 60, "Less-than sign"], [">", "gt", 62, "Greater-than sign"], ["&", "amp", 38, "Ampersand"], ['"', "quot", 34, "Quotation mark"], ["'", "apos", 39, "Apostrophe"],
  ["©", "copy", 169, "Copyright"], ["®", "reg", 174, "Registered trademark"], ["™", "trade", 8482, "Trademark"], ["€", "euro", 8364, "Euro"], ["£", "pound", 163, "Pound"], ["¥", "yen", 165, "Yen"], ["¢", "cent", 162, "Cent"],
  ["—", "mdash", 8212, "Em dash"], ["–", "ndash", 8211, "En dash"], ["…", "hellip", 8230, "Ellipsis"], ["«", "laquo", 171, "Left angle quote"], ["»", "raquo", 187, "Right angle quote"],
  ["×", "times", 215, "Multiply"], ["÷", "divide", 247, "Divide"], ["±", "plusmn", 177, "Plus-minus"], ["°", "deg", 176, "Degree"], ["µ", "micro", 181, "Micro"],
  ["α", "alpha", 945, "Greek alpha"], ["β", "beta", 946, "Greek beta"], ["γ", "gamma", 947, "Greek gamma"], ["δ", "delta", 948, "Greek delta"], ["ω", "omega", 969, "Greek omega"], ["π", "pi", 960, "Greek pi"], ["σ", "sigma", 963, "Greek sigma"],
  ["♥", "hearts", 9829, "Heart suit"], ["♠", "spades", 9824, "Spade suit"], ["♣", "clubs", 9827, "Club suit"], ["♦", "diams", 9830, "Diamond suit"], ["★", "starf", 9733, "Black star"], ["✓", "check", 10003, "Check mark"], ["✗", "cross", 10007, "Cross mark"],
  ["←", "larr", 8592, "Left arrow"], ["→", "rarr", 8594, "Right arrow"], ["↑", "uarr", 8593, "Up arrow"], ["↓", "darr", 8595, "Down arrow"], ["↔", "harr", 8596, "Left-right arrow"],
  ["¡", "iexcl", 161, "Inverted exclamation"], ["§", "sect", 167, "Section"], ["¨", "uml", 168, "Diaeresis"], ["ª", "ordf", 170, "Feminine ordinal"], ["¬", "not", 172, "Not sign"], ["¯", "macr", 175, "Macron"], ["²", "sup2", 178, "Superscript two"], ["³", "sup3", 179, "Superscript three"], ["´", "acute", 180, "Acute accent"], ["¶", "para", 182, "Pilcrow"], ["·", "middot", 183, "Middle dot"], ["¸", "cedil", 184, "Cedilla"], ["¹", "sup1", 185, "Superscript one"], ["º", "ordm", 186, "Masculine ordinal"], ["¼", "frac14", 188, "One quarter"], ["½", "frac12", 189, "One half"], ["¾", "frac34", 190, "Three quarters"], ["¿", "iquest", 191, "Inverted question"], ["À", "Agrave", 192, "A grave"], ["Á", "Aacute", 193, "A acute"], ["Â", "Acirc", 194, "A circumflex"], ["Ã", "Atilde", 195, "A tilde"], ["Ä", "Auml", 196, "A umlaut"], ["Å", "Aring", 197, "A ring"], ["Æ", "AElig", 198, "AE ligature"], ["Ç", "Ccedil", 199, "C cedilla"], ["È", "Egrave", 200, "E grave"], ["É", "Eacute", 201, "E acute"], ["Ê", "Ecirc", 202, "E circumflex"], ["Ë", "Euml", 203, "E umlaut"], ["Ì", "Igrave", 204, "I grave"], ["Í", "Iacute", 205, "I acute"], ["Î", "Icirc", 206, "I circumflex"], ["Ï", "Iuml", 207, "I umlaut"], ["Ð", "ETH", 208, "Eth"], ["Ñ", "Ntilde", 209, "N tilde"], ["Ò", "Ograve", 210, "O grave"], ["Ó", "Oacute", 211, "O acute"], ["Ô", "Ocirc", 212, "O circumflex"], ["Õ", "Otilde", 213, "O tilde"], ["Ö", "Ouml", 214, "O umlaut"], ["Ø", "Oslash", 216, "O slash"], ["Ù", "Ugrave", 217, "U grave"], ["Ú", "Uacute", 218, "U acute"], ["Û", "Ucirc", 219, "U circumflex"], ["Ü", "Uuml", 220, "U umlaut"], ["Ý", "Yacute", 221, "Y acute"], ["Þ", "THORN", 222, "Thorn"], ["ß", "szlig", 223, "Sharp s"],
] as const;

export default function HtmlEntitiesPage() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => entities.filter(([ch, name, dec, desc]) => `${ch} ${name} ${dec} ${desc}`.toLowerCase().includes(query.toLowerCase())).slice(0, 50), [query]);
  return <ToolShell slug="html-entities"><div className="space-y-5"><div><Label>Search entities</Label><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="amp, arrow, copyright..." /></div><div className="overflow-x-auto rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><table className="w-full text-sm"><thead><tr className="border-b border-zinc-200 text-left text-xs uppercase text-zinc-500 dark:border-zinc-800"><th className="px-4 py-2">Character</th><th className="px-4 py-2">Entity Name</th><th className="px-4 py-2">Decimal</th><th className="px-4 py-2">Hex</th><th className="px-4 py-2">Description</th><th /></tr></thead><tbody>{filtered.map(([ch, name, dec, desc]) => <tr key={name} className="border-b border-zinc-100 last:border-b-0 dark:border-zinc-800"><td className="px-4 py-2 text-lg">{ch}</td><td className="px-4 py-2 font-mono">&amp;{name};</td><td className="px-4 py-2 font-mono">&amp;#{dec};</td><td className="px-4 py-2 font-mono">&amp;#x{dec.toString(16).toUpperCase()};</td><td className="px-4 py-2 text-zinc-600 dark:text-zinc-400">{desc}</td><td className="px-4 py-2"><CopyButton value={`&${name};`} /></td></tr>)}</tbody></table></div></div></ToolShell>;
}
