"use client";

import { useMemo, useState } from "react";
import { CopyButton, Input, Label } from "@/components/ui";
import { ToolShell } from "@/components/ToolShell";

const mimeTypes = [
  ["html", "text/html", "Text", "HTML document"], ["htm", "text/html", "Text", "HTML document"], ["css", "text/css", "Text", "Stylesheet"], ["js", "text/javascript", "Text", "JavaScript"], ["mjs", "text/javascript", "Text", "JavaScript module"], ["json", "application/json", "Application", "JSON data"], ["xml", "application/xml", "Application", "XML data"], ["csv", "text/csv", "Text", "CSV data"], ["txt", "text/plain", "Text", "Plain text"], ["md", "text/markdown", "Text", "Markdown"],
  ["jpg", "image/jpeg", "Image", "JPEG image"], ["jpeg", "image/jpeg", "Image", "JPEG image"], ["png", "image/png", "Image", "PNG image"], ["gif", "image/gif", "Image", "GIF image"], ["svg", "image/svg+xml", "Image", "SVG image"], ["webp", "image/webp", "Image", "WebP image"], ["ico", "image/vnd.microsoft.icon", "Image", "Icon"], ["bmp", "image/bmp", "Image", "Bitmap"], ["tiff", "image/tiff", "Image", "TIFF image"], ["avif", "image/avif", "Image", "AVIF image"],
  ["mp3", "audio/mpeg", "Audio", "MP3 audio"], ["ogg", "audio/ogg", "Audio", "Ogg audio"], ["wav", "audio/wav", "Audio", "WAV audio"], ["flac", "audio/flac", "Audio", "FLAC audio"], ["aac", "audio/aac", "Audio", "AAC audio"], ["m4a", "audio/mp4", "Audio", "MPEG-4 audio"], ["opus", "audio/opus", "Audio", "Opus audio"], ["weba", "audio/webm", "Audio", "WebM audio"],
  ["mp4", "video/mp4", "Video", "MP4 video"], ["webm", "video/webm", "Video", "WebM video"], ["avi", "video/x-msvideo", "Video", "AVI video"], ["mov", "video/quicktime", "Video", "QuickTime video"], ["mkv", "video/x-matroska", "Video", "Matroska video"], ["mpeg", "video/mpeg", "Video", "MPEG video"], ["ogv", "video/ogg", "Video", "Ogg video"],
  ["pdf", "application/pdf", "Application", "PDF document"], ["zip", "application/zip", "Application", "ZIP archive"], ["gz", "application/gzip", "Application", "Gzip archive"], ["tar", "application/x-tar", "Application", "Tar archive"], ["7z", "application/x-7z-compressed", "Application", "7-Zip archive"], ["rar", "application/vnd.rar", "Application", "RAR archive"], ["wasm", "application/wasm", "Application", "WebAssembly"], ["bin", "application/octet-stream", "Application", "Binary data"], ["exe", "application/vnd.microsoft.portable-executable", "Application", "Windows executable"], ["rtf", "application/rtf", "Application", "Rich text"],
  ["woff", "font/woff", "Font", "WOFF font"], ["woff2", "font/woff2", "Font", "WOFF2 font"], ["ttf", "font/ttf", "Font", "TrueType font"], ["otf", "font/otf", "Font", "OpenType font"], ["eot", "application/vnd.ms-fontobject", "Font", "Embedded OpenType"],
  ["doc", "application/msword", "Office", "Word document"], ["docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Office", "Word document"], ["xls", "application/vnd.ms-excel", "Office", "Excel spreadsheet"], ["xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Office", "Excel spreadsheet"], ["ppt", "application/vnd.ms-powerpoint", "Office", "PowerPoint"], ["pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation", "Office", "PowerPoint"],
  ["form-data", "multipart/form-data", "Multipart", "Form upload"], ["byteranges", "multipart/byteranges", "Multipart", "Byte ranges"], ["graphql", "application/graphql", "Application", "GraphQL"], ["geojson", "application/geo+json", "Application", "GeoJSON"], ["ics", "text/calendar", "Text", "Calendar"], ["rss", "application/rss+xml", "Application", "RSS"], ["atom", "application/atom+xml", "Application", "Atom"], ["yaml", "application/yaml", "Application", "YAML"], ["yml", "application/yaml", "Application", "YAML"], ["sh", "application/x-sh", "Application", "Shell script"], ["php", "application/x-httpd-php", "Application", "PHP"], ["py", "text/x-python", "Text", "Python"], ["java", "text/x-java-source", "Text", "Java source"], ["c", "text/x-c", "Text", "C source"], ["cpp", "text/x-c++", "Text", "C++ source"], ["ts", "text/typescript", "Text", "TypeScript"], ["map", "application/json", "Application", "Source map"], ["apk", "application/vnd.android.package-archive", "Application", "Android package"], ["dmg", "application/x-apple-diskimage", "Application", "Apple disk image"], ["deb", "application/vnd.debian.binary-package", "Application", "Debian package"], ["rpm", "application/x-rpm", "Application", "RPM package"], ["swf", "application/x-shockwave-flash", "Application", "Flash"], ["epub", "application/epub+zip", "Application", "EPUB"], ["jar", "application/java-archive", "Application", "Java archive"],
] as const;

export default function MimeTypesPage() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => mimeTypes.filter((row) => row.join(" ").toLowerCase().includes(query.toLowerCase())), [query]);
  return <ToolShell slug="mime-types"><div className="space-y-5"><div><Label>Search MIME types</Label><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="json, image, application..." /></div><div className="overflow-x-auto rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><table className="w-full text-sm"><thead><tr className="border-b border-zinc-200 text-left text-xs uppercase text-zinc-500 dark:border-zinc-800"><th className="px-4 py-2">Extension</th><th className="px-4 py-2">MIME Type</th><th className="px-4 py-2">Category</th><th className="px-4 py-2">Notes</th><th /></tr></thead><tbody>{filtered.map(([ext, mime, cat, notes]) => <tr key={`${ext}-${mime}`} className="border-b border-zinc-100 last:border-b-0 dark:border-zinc-800"><td className="px-4 py-2 font-mono">.{ext}</td><td className="px-4 py-2 font-mono">{mime}</td><td className="px-4 py-2">{cat}</td><td className="px-4 py-2 text-zinc-600 dark:text-zinc-400">{notes}</td><td className="px-4 py-2"><CopyButton value={mime} /></td></tr>)}</tbody></table></div></div></ToolShell>;
}
